openrouter_api_key: ENC[AES256_GCM,data:ftI4+tcANlvPMTd9YJuTrzn6/rN1Lh7LFfkj4Dak+K5iEUhUq/24rXZNKPpPP+4gv0JzFhLMka95IG1nJEN6cD053u1JCZOJmg==,iv:5dWbCNE0wB+/My/wZWC9QmdQUFT0d8h8DovcFQivmKI=,tag:xuRW90fqUxduMj8b9a9MkA==,type:str]
openrouter_model: ENC[AES256_GCM,data:QDv28oaPJYp4I+90bjWsuaExEbcKFX57s8f1GOH2fLH2UWIkxUk=,iv:fsdWsi+EV0h14IvDEHTsLh6ILF/snW1Cr7snm/x4Ezw=,tag:ehoB9y/CogsdRozADK9gCQ==,type:str]
groq_api_key: ENC[AES256_GCM,data:TTpEHa74icUDqve56isCqLnAgJ7tVAGLEBTJ7o89uloNaZH1ebuV8CeUkegFYIBWeLOYy+j15EI=,iv:bK13+EBVszso39AM4s+fVo8NJ3yn+XIIpBBOWlqMePQ=,tag:gsKHb0+M81GN76iDByThzA==,type:str]
groq_model: ENC[AES256_GCM,data:lOexaBfeYOj3mfNtLO5rRo4caQ==,iv:PKx4LEDW9nPFsbJTMaqnqVCrOCMXUATIP+16F3qaB/0=,tag:gdJ176uBC/GVBZkcy86miA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UktXRUU2MjJCNmE1N2lQ
            NnFMUnpVcVA3WnFPY0JSdVlaMTl0ZXlSdkZvCkw3TnJEMGJVMlZ1amRSQlZNMCth
            TUxtcFJqYm5VWlNVN09nQ3FKU1hCUTgKLS0tIFhodVl6MTV3dzRYOXVBU2RRNUo5
            aTdOaDJjVWJRK21MTExDVTBRMDdxQ2cKkorFQ0KGA2xF5l2C0qBpQvuun0i82tk8
            JCEdIpyrwU3vvJsGpOxynZpxXbD4HiJ81Pt9GjSHylisKkScM+v6Zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wp8kgtd5jnzy37hlxy54erzms8zek5ae2x3a9a467p3ereu8e5yq8w43lp
    lastmodified: "2026-09-09T03:28:00Z"
    mac: ENC[AES256_GCM,data:p51RJWvE45jncOTw8ab48EoXsCL4TAeEEvSZJ/zCEUS64iR1bXIc4GulwSKi83MUi4JrDbJnF4VKFf/djz35K+7GbLA5ZXMDRlzXUxRBklnvrNIUjof40jP9pUziwcw77+4GPkroGn20ZnroAs28K6hKq3sdCCDnlV5GbKUKrVA=,iv:NdCu0RpTNhN2FMTbojt8WQPsmrJ7xrf6zlQ9/sx/kaU=,tag:I6RLN95O5qh4iTcXwkSh7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
